Indexer ES document id
DigitalPebble/storm-crawler pull request #1028
Opened 2023-01-05 09:20 UTC by Mikwiss

Hi @jnioche,

I saw the https://github.com/DigitalPebble/storm-crawler/issues/1025 issue and your answer related to https://github.com/DigitalPebble/storm-crawler/issues/671. That's was exactly the purpose of this PR !

In our case we use a random UUID to store the content (to keep all data). We add a new boolean parameter to handle this : `es.indexer.id.random`. The `getDocumentId()` can also be overrided to create any ID with metadata.

Signed-off-by: Mathieu Bret <mikwiss00@gmail.com>

Thanks for contributing to StormCrawler, your efforts are appreciated!

Developer Certificate of Origin
===============================

By contributing to StormCrawler, you accept and agree to the following terms and conditions (the *Developer Certificate of Origin*) for your present and future contributions submitted to StormCrawler. 
Please refer to the *Developer Certificate of Origin* section in [`CONTRIBUTING.md`](CONTRIBUTING.md) for details.

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

Before opening a PR, please check that: 

* You've squashed your commits into a single one
* You've described what the PR does or at least point to a related issue
* You've signed-ff your commits with 'git commit -s'
* The code is properly formatted with 'mvn git-code-format:format-code -Dgcf.globPattern=**/*'

Thanks!

2023-01-05 09:25 UTC, rzo1 commented
I am wondering, if it would be enough to provide

 ```
 protected String getDocumentID(Metadata metadata, String normalisedUrl) {
 //Return current default
}
```

so user's can override as needed without introducing a new config option?

2023-01-05 09:31 UTC, Mikwiss commented
It's enough indeed ! Maybe I am the only one to want keep data :)

2023-01-06 09:10 UTC, jnioche commented
Yes that would work as well

On Thu, 5 Jan 2023, 09:25 Richard Zowalla, ***@***.***> wrote:

> I am wondering, if it would be enough to provide
>
>  protected String getDocumentID(Metadata metadata, String normalisedUrl) {
>
> //Return current default
>
> }
>
>
> so user's can override as needed without introducing a new config option?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DigitalPebble/storm-crawler/pull/1028#issuecomment-1371972628>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABVJT2RETPXTE3FU25QNZLWQ2HQPANCNFSM6AAAAAATRXCML4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-06 18:06 UTC, rzo1 approved these changes

2023-01-07 16:18 UTC, jnioche commented
We'll need this for the other modules (SOLR, OpenSearch etc...) so I'd rather we did it for all of them in one go.
The new method could go in _AbstractIndexerBolt_ with the default implementation there, then call it in each implementation.

2023-01-08 07:49 UTC, rzo1 commented
> We'll need this for the other modules (SOLR, OpenSearch etc...) so I'd rather we did it for all of them in one go.
> The new method could go in _AbstractIndexerBolt_ with the default implementation there, then call it in each implementation.

+1

2023-01-10 13:55 UTC, Mikwiss commented
Hi guys, 

I made the change, but I'm not sure about _solr_ and _sql_ (despite changes don't change the behavior).

2023-01-10 15:43 UTC, jnioche requested changes

2023-01-10 15:43 UTC, jnioche commented on external/solr/src/main/java/com/digitalpebble/stormcrawler/solr/bolt/IndexerBolt.java
> +                doc.addField(fieldNameForURL(), getDocumentID(metadata, normalisedurl));
This is to store the URL, not the doc ID. I don't think we should call getDocumentID here, even if it returns the normalised URL.

2023-01-10 15:43 UTC, jnioche commented on external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/IndexerBolt.java
> +                preparedStmt.setString(1, getDocumentID(metadata, normalisedurl));
same as above, this is about the URL, not the docID

2023-01-10 17:17 UTC, merged

2023-01-10 17:17 UTC, jnioche commented
thanks @Mikwiss!