Refactoring
DigitalPebble/storm-crawler pull request #1052
Opened 2023-04-06 03:37 UTC by gabbar23

This pull request includes many refactorings that improve the quality and readability of the codebase. Specifically, I have used the following techniques to enhance the code:

- Extract Method: This technique involves breaking down a significant method into smaller, more manageable pieces. Doing so makes the code easier to understand and maintain, and the smaller methods can be reused in other parts of the codebase.

- Rename Method/Variable: This technique involves giving more meaningful names to methods and variables, which helps in understanding the purpose and functionality of the code. By doing so, the code becomes more expressive and easier to comprehend.

- Decompose Conditional: This technique involves breaking down complex conditional statements into smaller, more manageable parts. Doing so makes the code more readable and maintainable, and the more minor conditions can be reused in other parts of the codebase.

- Extract Class: This technique separates a large class into smaller, more specialized classes. Doing so makes the code more modular, and the individual classes can be reused in other parts of the codebase.
 
- Replace Conditional with Polymorphism: This technique replaces complex conditional statements with polymorphic behavior. Doing so makes the code more modular and extensible, and the individual classes can be reused in other parts of the codebase.
 
- Push-Down Variable/Method: This technique involves moving a variable or method from a superclass to a subclass. Doing so makes the code more modular, and the individual classes can be reused in other parts of the codebase.

2023-04-18 08:13 UTC, rzo1 requested changes
Can you sign-off your commits (as stated in the README) ? In addition, I added some more comments.

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/bolt/FeedParserBolt.java
> +    private boolean SHOULD_SNIFF_FOR_FEED  = false;
This isn't a constant, why do we rename it?

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/CharacterEscaper.java
> +package com.digitalpebble.stormcrawler.filtering.basic;
Missing license header

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/ControlCharacterEscaper.java
> +package com.digitalpebble.stormcrawler.filtering.basic;
Missing license header

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/parse/NodeVisitorTraverser.java
> +package com.digitalpebble.stormcrawler.parse;
Missing license header

2023-04-18 08:13 UTC, rzo1 commented on external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ScrollSpout.java
> +    //Rfactored by Amanjot Singh
Should be removed.

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/ControlCharacterEscaper.java
> +public class ControlCharacterEscaper implements CharacterEscaper {
This change opens a way for testability. Could you add a JUnit5 test?

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/NonControlCharacterEscaper.java
> +    public String escape(byte b) {
This change opens a way for testability. Could you add a JUnit5 test?

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/parse/NodeVisitorTraverser.java
> +    public static void traverse(
This change opens a way for testability. Could you add a JUnit5 test?

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/parse/NodeVisitorTraverser.java
> +    public static void traverse(
Do we need `static` here? (after we have extracted the class?)

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/parse/NodeVisitorTraverser.java
> +    static void appendNormalisedText(final StringBuilder accum, final TextNode textNode) {
see above. Perhaps add a JUnit test and remove static?

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/parse/NodeVisitorTraverser.java
> +    static boolean preserveWhitespace(Node node) {
see above. Perhaps add a JUnit test and remove static?

2023-04-18 08:13 UTC, rzo1 commented on external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ScrollSpout.java
> -        // dump query to log
any reason for removing the comment?

2023-04-18 08:13 UTC, rzo1 commented on external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCSpout.java
> +}
Change is unclear to me?

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/bolt/URLPartitionerBolt.java
> -        // Register a "MultiCountMetric" to count different events in this bolt
IMHO we should retain the comments

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/bolt/URLPartitionerBolt.java
> -                    // This method is called just after a new entry has been added
IMHO we should retain the comments

2023-04-18 08:13 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/bolt/URLPartitionerBolt.java
> -        // If the cache is to be used by multiple threads,
IMHO we should retain the comments

2023-04-27 15:00 UTC, jnioche commented
Closing for lack of activity. Please feel free to reopen

2023-04-27 15:00 UTC, closed without merging