BasicURLNormalizer .unmangleQueryString() returns invalid results if "&" symbol in a parents path #1059
DigitalPebble/storm-crawler pull request #1062
Opened 2023-05-02 22:28 UTC by syefimov

BasicURLNormalizer .unmangleQueryString() returns invalid results if "&" symbol in a parents path #1059

Analyze only last item in a URL path. Test added.

2023-05-03 07:34 UTC, rzo1 commented on core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/BasicURLNormalizer.java
> +        int firstAmp = pathElements[pathElements.length - 1].indexOf('&');
I don't recall the complete normalizer code, so the following might not happen (as other methods guard against it...)

If `pathElements` is empty, we will access index `-1`. While this case might not happen in production (assuming every encountered URL starts with a protocol), we should be robust against everything we encounter in the wild. Can we guard it with a `pathElements.length > 0` check?

2023-05-03 07:40 UTC, rzo1 commented
Nevermind, need more coffee :-)

2023-05-03 13:58 UTC, jnioche requested changes

2023-05-08 14:52 UTC, jnioche approved these changes

2023-05-08 14:53 UTC, merged

2023-05-08 14:53 UTC, jnioche commented
thanks @syefimov